name: videopsalm_to_sog_converter
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.7 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
dependencies:
  build_runner: ^2.3.3
  json5: ^0.8.0
  json_annotation: ^4.8.0
  json_serializable: ^6.6.1
  logger: ^1.3.0
